const phases = {
  p1:{label:'Phase 1',title:'Attention + Product',body:'Create recurring public signals and give the audience a practical first implementation path. The content engine generates demand while T1A turns attention into action.',pills:['Content engine','T1A accelerator','Lead capture','Case studies','Sponsor inventory']},
  p2:{label:'Phase 2',title:'Activation + Community',body:'Give businesses three clear ways to engage: learn it, experience it with the network, or hire AMP IRL to install it. T1A, T1B and T1C are parallel entry points—not a forced ladder.',pills:['T1A · Teach','T1B · Connect','T1C · Build','Events','Membership']},
  p3:{label:'Phase 3',title:'Analysis + Systems',body:'Diagnose the real bottleneck, validate what people actually implement, introduce SOS as the operating layer, and identify the users ready to become co-builders.',pills:['Diagnostic','SOS','90-day validation','Tier 3 builders','Custom AI/workflows']},
  p4:{label:'Phase 4',title:'Leadership + Expansion',body:'Protect the highest-value room for proven operators, then scale through leaders who have already demonstrated implementation, judgment and contribution inside the system.',pills:['Tier 4 Farmhouse','Flagship experiences','Tier 5 expansion','Chapters','Licensing + leaders']}
};
const tiers = {
  t1a:{code:'TIER 1A',name:'90-Day Growth Accelerator',price:'Working benchmark · $297',tagline:'Teach the operating principles and make implementation visible.',purpose:'A practical DIY entry point for owners willing to do the work. The goal is installed behavior—not content consumption.',fit:'Owners who need structure, milestones and guided implementation before they need a full service engagement.',items:['Short-form video academy','Implementation guide + templates','Pocket AI / guided Q&A','Milestones + checkpoints','Marketing, sales, AI and operations prompts','Path to diagnostic / SOS / services'],bottom:'T1A teaches. It creates a low-friction first win, reveals who actually implements, and produces proof that feeds every later tier.'},
  t1b:{code:'TIER 1B',name:'The Farm Community',price:'Working benchmark · ≈ $500/year',tagline:'Create useful relationships, live experiences and a qualification engine.',purpose:'A Chicago-first community built around fun + function: practical workshops, events, dinners, activations, introductions and member opportunities.',fit:'Owners who grow faster with peers, partners, referrals, visibility and recurring real-world contact.',items:['Member-only events + workshops','Preferred AMP IRL event pricing','Referral + vendor pathways','Speaker + content opportunities','Problem-solving sessions','Leadership progression + recognition'],bottom:'T1B connects. The community is both a revenue vertical and a place to identify future clients, partners, speakers, builders and chapter leaders.'},
  t1c:{code:'TIER 1C',name:'Business Solutions',price:'Project / retainer / rev-share',tagline:'Install the things the client should not have to build alone.',purpose:'Top-to-bottom implementation through AMP IRL and approved partners. This is where strategy turns into media, events, systems and measurable execution.',fit:'Businesses with a clear need, budget and urgency who want the team to build rather than teach them every step.',items:['Branding + content production','Websites + funnels','Automation + AI agents','Events + experiential marketing','Direct response + lead generation','Review generation + sales enablement','Production + livestreaming','Approved specialist partners'],bottom:'T1C builds. It can be the first entry point for a qualified client or the natural next step after T1A/T1B reveals a need.'},
  t2:{code:'TIER 2',name:'Analysis + SOS',price:'Original benchmarks · Diagnostic ≈ $497 · SOS founding lane $97',tagline:'Diagnose the bottleneck, validate behavior and install the operating layer.',purpose:'Tier 2 is not “the beta tier.” Its permanent job is analysis + SaaS adoption. Validation cohorts are one workstream inside it.',fit:'Businesses that need to know what is actually blocking growth—or that are ready to centralize workflows, memory, follow-up and operating context.',items:['Custom business diagnostic','90-day recommendation','SOS onboarding','Baseline + 30/60/90-day checkpoints','Usage + friction analysis','Launch / revise / narrow / rebuild gate'],bottom:'The story is not complete when AMP IRL gives a client something. It is complete when the client uses it and observable behavior changes.'},
  t3:{code:'TIER 3',name:'SOS Builder',price:'Original benchmark · $297/month',tagline:'Turn advanced users into co-builders of reusable systems.',purpose:'Tier 3 gives operators deeper platform access, custom workflow development and a role in improving systems that can create value across the network.',fit:'Implementation-minded owners and operators who can articulate workflows, test systems, give useful feedback and help create reusable patterns.',items:['Advanced SOS access','Custom onboarding AI agent','Workflow discovery + build','Test + document loops','Builder / dev community','Credits, priority and contributor payback'],bottom:'When a custom item helps the broader community, the contributor should receive meaningful value back—through credits, access, recognition, support or economics.'},
  t4:{code:'TIER 4',name:'The Farmhouse',price:'Invitation / premium',tagline:'Protect the pinnacle for proven operators and highest-leverage work.',purpose:'A premium room for founders who have reduced operational chaos and earned deeper access through fit, implementation, contribution and judgment.',fit:'Established founders and leaders ready for strategic depth, private build days, retreats, introductions and higher-level problem solving.',items:['Private strategy rooms','Retreats + destination experiences','Founder roundtables','High-level partner introductions','Advanced planning + legacy work','Selective investment / venture conversations when appropriate'],bottom:'Tier 4 is scarce by design. Access is based on readiness and fit—not simply the ability to buy a ticket.'},
  t5:{code:'TIER 5',name:'Expansion',price:'Market / chapter economics',tagline:'Scale through proven people, not through random geography.',purpose:'Take the repeatable AMP IRL playbook into new markets only after the local model has enough proof, systems, leadership and economics to travel.',fit:'Proven Tier 3/Tier 4 leaders, strategic partners or operators capable of carrying the standards of the ecosystem into another market.',items:['Leader-first market selection','Repeatable event playbook','Membership + sponsor playbook','SOS + services model','Media/content system','Licensing / chapter economics','Quality controls + reporting'],bottom:'Choose the leader first, then the city. Proven people scale the brand; geography alone does not.'}
};
const pTabs=document.getElementById('phaseTabs'), pPanel=document.getElementById('phasePanel');
Object.entries(phases).forEach(([k,p],i)=>{const b=document.createElement('button');b.className='phase-btn'+(i===0?' active':'');b.dataset.phase=k;b.innerHTML=`<small>${p.label}</small><strong>${p.title}</strong>`;b.onclick=()=>renderPhase(k);pTabs.appendChild(b)});
function renderPhase(k){document.querySelectorAll('.phase-btn').forEach(b=>b.classList.toggle('active',b.dataset.phase===k));const p=phases[k];pPanel.innerHTML=`<h3>${p.title}</h3><p>${p.body}</p><div class="phase-pills">${p.pills.map(x=>`<span class="pill">${x}</span>`).join('')}</div>`}
renderPhase('p1');
const tNav=document.getElementById('tierNav'), tDetail=document.getElementById('tierDetail');
Object.entries(tiers).forEach(([k,t],i)=>{const b=document.createElement('button');b.className='tier-btn'+(i===0?' active':'');b.dataset.tier=k;b.innerHTML=`<span class="code">${t.code}</span><strong>${t.name}</strong>`;b.onclick=()=>renderTier(k);tNav.appendChild(b)});
function renderTier(k){document.querySelectorAll('.tier-btn').forEach(b=>b.classList.toggle('active',b.dataset.tier===k));const t=tiers[k];tDetail.innerHTML=`<div class="tier-top"><div><div class="tier-code">${t.code}</div><h3>${t.name}</h3><div class="tier-tagline">${t.tagline}</div></div><div class="price">${t.price}</div></div><div class="detail-grid"><div class="detail-box"><h4>Purpose</h4><p>${t.purpose}</p></div><div class="detail-box"><h4>Best fit</h4><p>${t.fit}</p></div></div><div class="deliverables">${t.items.map(x=>`<div class="deliv">${x}</div>`).join('')}</div><div class="tier-bottom">${t.bottom}</div>`}
renderTier('t1a');